m20_root/characters/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',
         views.CharacterListView.as_view(), name='index'),
    path(
        'characters/<slug:slug>/',
        views.CharacterDetailView.as_view(), name='character_detail'),
]

m20_root/m20_site/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('characters.urls')),
]

m20_root/characters/models.py
from django.db import models
from django.db.models import Sum
import uuid
import math

WEAPON_TYPE = (
    ('L', 'Light'),
    ('1H', 'One-Handed'),
    ('2H', 'Two-Handed'),
    ('R', 'Ranged'),
)

ARMOR_TYPE = (
    ('L', 'Light'),
    ('M', 'Medium'),
    ('H', 'Heavy'),
    ('S', 'Shield'),
)

# Create your models here.


class Player(models.Model):
    class Meta:
        ordering = ['name']
        verbose_name = 'Player'
        verbose_name_plural = 'Players'
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=254, unique=True)
    is_active = models.BooleanField(default=True)
    slug = models.SlugField(default=uuid.uuid4)

    def __str__(self):
        return self.name


class Class(models.Model):
    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Classes'
    name = models.CharField(max_length=20)
    abilities = models.TextField(blank=True)
    attack_bonus = models.IntegerField(default=0)
    phys_bonus = models.IntegerField(default=0)
    sub_bonus = models.IntegerField(default=0)
    know_bonus = models.IntegerField(default=0)
    com_bonus = models.IntegerField(default=0)
    light_armor = models.BooleanField(default=False)
    medium_armor = models.BooleanField(default=False)
    heavy_armor = models.BooleanField(default=False)
    shields = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Race(models.Model):
    class Meta:
        ordering = ['name']
    name = models.CharField(max_length=20)
    abilities = models.TextField(blank=True)
    skill_roll_bonus = models.IntegerField('Skill Roll Bonus', default=0)
    str_bonus = models.IntegerField('STR Bonus', default=0)
    dex_bonus = models.IntegerField('DEX Bonus', default=0)
    mind_bonus = models.IntegerField('MIND Bonus', default=0)

    def __str__(self):
        return self.name


class Weapon(models.Model):
    class Meta:
        ordering = ['name']
    name = models.CharField(max_length=50)
    type = models.CharField(max_length=10, choices=WEAPON_TYPE)
    cost = models.CharField(max_length=10, blank=False, default='-')
    damage = models.CharField(max_length=10, blank=False, default='-')
    range = models.CharField(max_length=10, blank=False, default='-')

    def __str__(self):
        return self.name


class Armor(models.Model):
    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Armor'
    name = models.CharField(max_length=50)
    type = models.CharField(max_length=10, choices=ARMOR_TYPE)
    cost = models.CharField(max_length=10, blank=False, default='-')
    ac_bonus = models.IntegerField('AC Bonus', default=1)

    def __str__(self):
        return self.name


class Gear(models.Model):
    class Meta:
        ordering = ['name']
        verbose_name = 'Item'
        verbose_name_plural = 'Item'
    name = models.CharField(max_length=50)
    cost = models.CharField(max_length=10, blank=False, default='-')

    def __str__(self):
        return self.name


class GearPack(models.Model):
    class Meta:
        ordering = ['name']
        verbose_name = 'Gear Pack'
        verbose_name_plural = 'Gear Packs'
    name = models.CharField(max_length=50)
    cost = models.CharField(max_length=10, blank=False, default='-')
    gear = models.ManyToManyField(
        Gear, blank=True, through='GearInPack')

    def __str__(self):
        return self.name


class Clothing(models.Model):
    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Clothing'
    name = models.CharField(max_length=50)
    cost = models.CharField(max_length=10, blank=False, default='-')

    def __str__(self):
        return self.name


class Character(models.Model):
    class Meta:
        ordering = ['name']
    name = models.CharField(max_length=100)
    slug = models.SlugField(default=uuid.uuid4)
    player = models.ForeignKey(
        Player, blank=True, null=True, on_delete=models.CASCADE)
    race = models.ForeignKey(Race, on_delete=models.PROTECT)
    character_class = models.ForeignKey(
        Class, verbose_name='Class', on_delete=models.PROTECT)
    level = models.IntegerField(default=1)
    hit_points = models.IntegerField('Hit Points', default=1)
    xp = models.IntegerField('XP', default=0)
    str = models.IntegerField('STR', default=10)
    dex = models.IntegerField('DEX', default=10)
    mind = models.IntegerField('MIND', default=10)
    armor = models.ManyToManyField(Armor, blank=True)
    weapons = models.ManyToManyField(Weapon, blank=True)
    gear = models.ManyToManyField(
        Gear, blank=True, through='CharacterGear')
    clothing = models.ForeignKey(
        Clothing, blank=True, null=True, on_delete=models.PROTECT)
    copper = models.IntegerField(default=0)
    silver = models.IntegerField(default=0)
    gold = models.IntegerField(default=0)
    platinum = models.IntegerField(default=0)
    notes = models.TextField(blank=True)

    @property
    def armor_class(self):
        ac = (10 + math.floor((self.dex - 10)/2))
        if self.armor.count() > 0:
            ac += self.armor.all().aggregate(
                Sum('ac_bonus')).get('ac_bonus__sum')
        return ac

    @ property
    def str_bonus(self):
        return int((self.str - 10) / 2)

    @ property
    def dex_bonus(self):
        return int((self.dex - 10) / 2)

    @ property
    def mind_bonus(self):
        return int((self.mind - 10) / 2)

    @ property
    def phys(self):
        return (
            int(self.level) +
            int(self.character_class.phys_bonus) +
            int(self.race.skill_roll_bonus))

    @ property
    def sub(self):
        return (
            int(self.level) +
            int(self.character_class.sub_bonus) +
            int(self.race.skill_roll_bonus))

    @ property
    def know(self):
        return (
            int(self.level) +
            int(self.character_class.know_bonus) +
            int(self.race.skill_roll_bonus))

    @ property
    def com(self):
        return (
            int(self.level) +
            int(self.character_class.com_bonus) +
            int(self.race.skill_roll_bonus))

    @ property
    def melee_bonus(self):
        return (
            int(self.level) +
            int(self.character_class.attack_bonus) +
            int((self.character_class.attack_bonus * (self.level / 5))) +
            int((self.str - 10) / 2))

    @ property
    def ranged_bonus(self):
        return (
            self.level +
            int(self.character_class.attack_bonus) +
            int((self.character_class.attack_bonus * (self.level / 5))) +
            int((self.dex - 10) / 2))

    @ property
    def magic_bonus(self):
        return self.level + int((self.mind - 10) / 2)

    def get_absolute_url(self):
        return "/characters/%s" % self.slug

    def __str__(self):
        return self.name


class CharacterGear(models.Model):
    class Meta:
        ordering = ['gear__name']
        verbose_name = 'Item'
        verbose_name_plural = 'Items'
    character = models.ForeignKey(Character, on_delete=models.CASCADE)
    gear = models.ForeignKey(
        Gear, verbose_name='Item', on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return self.gear.name


class GearInPack(models.Model):
    class Meta:
        ordering = ['gear__name']
        verbose_name = 'Item'
        verbose_name_plural = 'Items'
    gearpack = models.ForeignKey(GearPack, on_delete=models.CASCADE)
    gear = models.ForeignKey(
        Gear, verbose_name='Item', on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return self.gear.name

m20_root/characters/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from .models import Character

# Create your views here.


def index(request):
    return HttpResponse("<h1>microlite20 Characters</h1>")


class CharacterDetailView(generic.DetailView):
    model = Character
    template_name = 'characters/character_detail.html'


class CharacterListView(generic.ListView):
    model = Character
    template_name = 'characters/index.html'

m20_root/characters/templates/characters/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block pagetitle %}{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <style>@media print { .container { font-size: 16pt; } }</style>
</head>
<body>
{% block content %}{% endblock %}
</body>

m20_root/characters/templates/characters/character_detail.html
{% extends "characters/base.html" %}
{% block pagetitle %}Microlite 20 Character Sheet{% endblock %}
{% block content %}
<div class="container my-3">
    <div class="row bg-dark text-white pt-2">
        <div class="col">
            <h4 class="text-uppercase">Microlite 20 Character Sheet</h4>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-12 col-md-6">
            <div class="row">
                <div class="col-3 font-weight-bold">
                    Name:
                </div>
                <div class="col">
                    {{ character.name }}
                </div>
            </div>
            <div class="row">
                <div class="col-3 font-weight-bold">
                    Race:
                </div>
                <div class="col">
                    {{ character.race }}
                </div>
            </div>
            <div class="row">
                <div class="col-3 font-weight-bold">
                    Class:
                </div>
                <div class="col">
                    {{ character.character_class }}
                </div>
            </div>
        </div>
        <div class="col-12 col-md-6">
            <div class="row">
                <div class="col-3 col-md-3 font-weight-bold">
                    Player:
                </div>
                <div class="col">
                    {{ character.player }}
                </div>
            </div>
            <div class="row">
                <div class="col-3 col-md-3 font-weight-bold">
                    Level:
                </div>
                <div class="col-2">
                    {{ character.level }}
                </div>
                <div class="col-2 font-weight-bold">
                    XP:
                </div>
                <div class="col-1">
                    {{ character.xp }}
                </div>
            </div>
            <div class="row">
                <div class="col-3 col-md-3 font-weight-bold">
                    HP:
                </div>
                <div class="col-2">
                    {{ character.hit_points }}
                </div>
                <div class="col-2 font-weight-bold">
                    AC:
                </div>
                <div class="col-1">
                    {{ character.armor_class }}
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            {{ character.character_class.abilities }}
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-md-4">
            <div class="row my-3">
                <div class="col bg-dark text-white font-weight-bold text-uppercase">
                    Stats (Bonus)
                </div>
            </div>
            <div class="row">
                <div class="col-4 font-weight-bold">
                    STR:
                </div>
                <div class="col-1">
                    {{ character.str }}
                </div>
                <div class="col">
                    ({{character.str_bonus|stringformat:"+i" }})
                </div>
            </div>
            <div class="row">
                <div class="col-4 font-weight-bold">
                    DEX:
                </div>
                <div class="col-1">
                    {{ character.dex }}
                </div>
                <div class="col">
                    ({{character.dex_bonus|stringformat:"+i" }})
                </div>
            </div>
            <div class="row">
                <div class="col-4 font-weight-bold">
                    MIND:
                </div>
                <div class="col-1">
                    {{ character.mind }}
                </div>
                <div class="col">
                    ({{character.mind_bonus|stringformat:"+i" }})
                </div>
            </div>
        </div>
        <div class="col-12 col-md-4">
            <div class="row my-3">
                <div class="col bg-dark text-white font-weight-bold text-uppercase">
                    Skill Rank
                </div>
            </div>
            <div class="row">
                <div class="col-4 font-weight-bold">
                    phys:
                </div>
                <div class="col">
                    {{ character.phys }}
                </div>
            </div>
            <div class="row">
                <div class="col-4 font-weight-bold">
                    sub:
                </div>
                <div class="col">
                    {{ character.sub }}
                </div>
            </div>
            <div class="row">
                <div class="col-4 font-weight-bold">
                    know:
                </div>
                <div class="col">
                    {{ character.know }}
                </div>
            </div>
            <div class="row">
                <div class="col-4 font-weight-bold">
                    com:
                </div>
                <div class="col">
                    {{ character.com }}
                </div>
            </div>
        </div>
        <div class="col-12 col-md-4">
            <div class="row my-3">
                <div class="col bg-dark text-white font-weight-bold text-uppercase">
                    Attack Bonus
                </div>
            </div>
            <div class="row">
                <div class="col-4 font-weight-bold">
                    Melee:
                </div>
                <div class="col">
                    {{ character.melee_bonus|stringformat:"+i" }}
                </div>
            </div>
            <div class="row">
                <div class="col-4 font-weight-bold">
                    Ranged:
                </div>
                <div class="col">
                    {{ character.ranged_bonus|stringformat:"+i" }}
                </div>
            </div>
            <div class="row">
                <div class="col-4 font-weight-bold">
                    Magic:
                </div>
                <div class="col">
                    {{ character.magic_bonus|stringformat:"+i" }}
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-md-6">
            <div class="row my-3">
                <div class="col bg-dark text-white font-weight-bold text-uppercase">
                    Weapons
                </div>
            </div>
            {% for weapon in character.weapons.all %}
            <div class="row">
                <div class="col">
                    <span class="font-weight-bold">{{ weapon.name }}</span>
                    (dmg: {{ weapon.damage }}, range: {{ weapon.range }})
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="col-12 col-md-6">
            <div class="row my-3">
                <div class="col bg-dark text-white font-weight-bold text-uppercase">
                    Armor
                </div>
            </div>
            {% for armor in character.armor.all %}
            <div class="row">
                <div class="col">
                    <span class="font-weight-bold">{{ armor.name }}</span>
                    (AC bonus: {{ armor.ac_bonus }})
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-md-6">
            <div class="row my-3">
                <div class="col bg-dark text-white font-weight-bold text-uppercase">
                    Inventory
                </div>
            </div>
            <div class="row">
                {% for item in character.charactergear_set.all %}
                <div class="col-12 col-lg-6">
                    {{ item.gear.name }} ({{ item.quantity }})
                </div>
                {% endfor %}
            </div>
            <div class="row mt-2">
                <div class="col-3 font-weight-bold">
                    Clothing:
                </div>
                <div class="col-9">
                    {{ character.clothing }}
                </div>
                <div class="col-3 font-weight-bold">
                    Currency:
                </div>
                <div class="col-9">
                    {{ character.platinum }}pp,
                    {{ character.gold }}gp,
                    {{ character.silver }}sp,
                    {{ character.copper }}cp
                </div>
            </div>
        </div>
        <div class="col-12 col-md-6">
            <div class="row my-3">
                <div class="col bg-dark text-white font-weight-bold text-uppercase">
                    Notes
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    {{ character.notes|linebreaks }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

m20_root/characters/templates/characters/index.html
{% extends "characters/base.html" %}
{% block pagetitle %}Microlite 20 Character Sheet{% endblock %}
{% block content %}
<div class="container my-3">
    <div class="row bg-dark text-white pt-2">
        <div class="col">
            <h4 class="text-uppercase">Microlite 20 Characters</h4>
        </div>
    </div>
    <div class="row mt-2">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Character Name</th>
                    <th>Class</th>
                    <th>Race</th>
                    <th>Level</th>
                </tr>
            </thead>
            <tbody>
                {% for character in character_list %}
                <tr>
                    <td>
                        <a href="characters/{{ character.slug }}">
                        {{ character.name }}</a>
                    </td>
                    <td>{{ character.character_class }}</td>
                    <td>{{ character.race }}</td>
                    <td>{{ character.level }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}